
from __future__ import annotations

from dataclasses import dataclass, asdict
import math


@dataclass(frozen=True)
class RaceEconomy:
    colonists_per_resource:int
    factory_output_per_10:int
    factory_build_cost:int
    operable_factories_per_10k:int
    factory_germanium_discount:bool
    mine_output_per_10:int
    mine_build_cost:int
    operable_mines_per_10k:int
    alternate_reality:bool=False

    def to_dict(self):
        return asdict(self)


def decode_race_economy(race) -> RaceEconomy:
    """
    StarsAPI PlayerBlock fullData mapping:

      [54] population efficiency, in hundreds of colonists/resource
      [55] resources produced by 10 factories
      [56] factory resource build cost
      [57] factories operable per 10,000 colonists
      [58] minerals produced by 10 mines
      [59] mine resource build cost
      [60] mines operable per 10,000 colonists
      [73] bit 7 = factory costs 1kT less Germanium

    StarsAPI's own "beefy" race writes 7, 15/5/25, 25/2/25.
    """
    native=getattr(race,"native",{}) or {}
    raw=list(native.get("economy_raw",[]) or [])
    pop_raw=int(native.get("population_efficiency_raw",10) or 10)
    flags=int(native.get("flags_73",0) or 0)

    # Conservative standard-race defaults if full race data is unavailable.
    while len(raw)<6:
        raw.append((10,10,10,10,5,10)[len(raw)])

    prt=str(getattr(race,"primary_trait","") or "")
    ar=("Alternate Reality" in prt) or int(native.get("prt_id",-1))==8

    return RaceEconomy(
        colonists_per_resource=max(100,pop_raw*100),
        factory_output_per_10=max(0,int(raw[0])),
        factory_build_cost=max(1,int(raw[1])),
        operable_factories_per_10k=max(0,int(raw[2])),
        factory_germanium_discount=bool(flags & 0x80),
        mine_output_per_10=max(0,int(raw[3])),
        mine_build_cost=max(1,int(raw[4])),
        operable_mines_per_10k=max(0,int(raw[5])),
        alternate_reality=ar,
    )


def installation_caps(population:int,economy:RaceEconomy) -> tuple[int,int]:
    """
    Current-population operating ceiling.

    Stars! defines the setting as "Every 10,000 colonists may operate up to N".
    Infrastructure above this ceiling provides no current operating benefit.
    """
    if economy.alternate_reality:
        return 0,0
    pop=max(0,int(population))
    factories=(pop*economy.operable_factories_per_10k)//10000
    mines=(pop*economy.operable_mines_per_10k)//10000
    return int(factories),int(mines)


def installation_status(planet,economy:RaceEconomy) -> dict:
    fcap,mcap=installation_caps(int(planet.population or 0),economy)
    factories=int(planet.factories or 0)
    mines=int(planet.mines or 0)
    return {
        "population":int(planet.population or 0),
        "factory_cap":fcap,
        "mine_cap":mcap,
        "factories":factories,
        "mines":mines,
        "factory_headroom":max(0,fcap-factories),
        "mine_headroom":max(0,mcap-mines),
        "factory_overbuilt":max(0,factories-fcap),
        "mine_overbuilt":max(0,mines-mcap),
        "factories_fully_utilized":factories>=fcap,
        "mines_fully_utilized":mines>=mcap,
    }


def estimated_operating_resources(planet,economy:RaceEconomy) -> dict:
    """
    Estimate the resources currently generated by population + OPERABLE factories.
    This is for planning/reporting only, not native accounting.
    """
    status=installation_status(planet,economy)
    operated_factories=min(status["factories"],status["factory_cap"])
    pop_resources=int(planet.population or 0)//max(1,economy.colonists_per_resource)
    factory_resources=(operated_factories*economy.factory_output_per_10)//10
    return {
        **status,
        "operated_factories":operated_factories,
        "population_resources":pop_resources,
        "factory_resources":factory_resources,
        "estimated_resources":pop_resources+factory_resources,
    }


# --- Population carrying capacity / growth ---

def theoretical_max_population(race) -> int:
    """
    Stars! nominal carrying capacity is 1,000,000 colonists, modified by race:
      HE   x 0.5
      JOAT x 1.2
      OBRM x 1.1

    These modifiers stack the same way StarsAPI's Race.getMaxPopulation() does.
    """
    native=getattr(race,"native",{}) or {}
    prt_id=int(native.get("prt_id",-1))
    prt=str(getattr(race,"primary_trait","") or "")
    lrts=set(native.get("lrts",[]) or [])

    max_pop=1_000_000.0
    if prt_id==0 or "Hyper Expansion" in prt:
        max_pop *= 0.5
    if prt_id==9 or "Jack of All Trades" in prt:
        max_pop *= 1.2
    if "OBRM" in lrts:
        max_pop *= 1.1
    return int(max_pop)


def planet_population_capacity(planet,race) -> int:
    """
    Green/yellow worlds use the race's carrying capacity.
    A red (negative-habitability) world uses Stars!' special 25,000 ceiling
    for crowding/death calculations.
    """
    hab=getattr(planet,"habitability",None)
    if hab is not None and int(hab) < 0:
        return 25_000
    return theoretical_max_population(race)


def population_capacity_fraction(planet,race) -> float:
    cap=max(1,planet_population_capacity(planet,race))
    # StarsAPI/Technical FAQ behavior uses CEIL to an integer capacity percent.
    pop=max(0,int(getattr(planet,"population",0) or 0))
    pct=math.ceil((pop/cap)*100.0)
    return pct/100.0


def projected_population_growth(planet,race) -> int:
    """
    Stars! crowding-aware annual population growth.

    Source model follows StarsAPI Star.CalculateGrowth:
      - <=25% capacity: nominal growth
      - 25-100%: crowding factor 16/9 * (1-capacity)^2
      - 100%: zero
      - over capacity: crowding deaths
      - growth/death is rounded to 100-colonist units

    Habitability is represented in our normalized model as -15..100%.
    """
    pop=max(0,int(getattr(planet,"population",0) or 0))
    if pop<=0:
        return 0

    hab_raw=getattr(planet,"habitability",None)
    if hab_raw is None:
        return 0
    hab=max(-1.0,min(1.0,float(hab_raw)/100.0))

    growth_rate=float(getattr(race,"growth_rate",0.15) or 0.15)
    native=getattr(race,"native",{}) or {}
    prt_id=int(native.get("prt_id",-1))
    prt=str(getattr(race,"primary_trait","") or "")
    if prt_id==0 or "Hyper Expansion" in prt:
        growth_rate *= 2.0

    capacity=population_capacity_fraction(planet,race)

    if hab < 0:
        growth=0.1*pop*hab
    elif capacity <= 0.25:
        growth=pop*growth_rate*hab
    elif capacity < 1.0:
        growth=pop*growth_rate*hab
        growth *= (16.0/9.0)*(1.0-capacity)*(1.0-capacity)
    elif capacity == 1.0:
        growth=0.0
    elif capacity < 4.0:
        growth=pop*(capacity-1.0)*-4.0/100.0
    else:
        growth=pop*-0.12

    # Vanilla Stars! tracks population in 100-colonist increments.
    final=int(growth)
    final=int(final/100)*100
    return final


def projected_next_population(planet,race) -> int:
    return max(0,int(getattr(planet,"population",0) or 0)+projected_population_growth(planet,race))
