
from __future__ import annotations

from dataclasses import dataclass, asdict
import math


MINERAL_TYPES = ("ironium", "boranium", "germanium")


@dataclass(frozen=True)
class RaceEconomy:
    colonists_per_resource:int
    factory_output_per_10:int
    factory_build_cost:int
    operable_factories_per_10k:int
    factory_germanium_discount:bool
    mine_output_per_10:int
    mine_build_cost:int
    operable_mines_per_10k:int
    alternate_reality:bool=False

    def to_dict(self):
        return asdict(self)


def decode_race_economy(race) -> RaceEconomy:
    """
    StarsAPI PlayerBlock fullData mapping:

      [54] population efficiency, in hundreds of colonists/resource
      [55] resources produced by 10 factories
      [56] factory resource build cost
      [57] factories operable per 10,000 colonists
      [58] minerals produced by 10 mines
      [59] mine resource build cost
      [60] mines operable per 10,000 colonists
      [73] bit 7 = factory costs 1kT less Germanium

    StarsAPI's own "beefy" race writes 7, 15/5/25, 25/2/25.
    """
    native=getattr(race,"native",{}) or {}
    raw=list(native.get("economy_raw",[]) or [])
    pop_raw=int(native.get("population_efficiency_raw",10) or 10)
    flags=int(native.get("flags_73",0) or 0)

    # Conservative standard-race defaults if full race data is unavailable.
    while len(raw)<6:
        raw.append((10,10,10,10,5,10)[len(raw)])

    prt=str(getattr(race,"primary_trait","") or "")
    ar=("Alternate Reality" in prt) or int(native.get("prt_id",-1))==8

    return RaceEconomy(
        colonists_per_resource=max(100,pop_raw*100),
        factory_output_per_10=max(0,int(raw[0])),
        factory_build_cost=max(1,int(raw[1])),
        operable_factories_per_10k=max(0,int(raw[2])),
        factory_germanium_discount=bool(flags & 0x80),
        mine_output_per_10=max(0,int(raw[3])),
        mine_build_cost=max(1,int(raw[4])),
        operable_mines_per_10k=max(0,int(raw[5])),
        alternate_reality=ar,
    )


def installation_caps(population:int,economy:RaceEconomy) -> tuple[int,int]:
    """
    Current-population operating ceiling.

    Stars! defines the setting as "Every 10,000 colonists may operate up to N".
    Infrastructure above this ceiling provides no current operating benefit.
    """
    if economy.alternate_reality:
        return 0,0
    pop=max(0,int(population))
    factories=(pop*economy.operable_factories_per_10k)//10000
    mines=(pop*economy.operable_mines_per_10k)//10000
    return int(factories),int(mines)


def installation_status(planet,economy:RaceEconomy) -> dict:
    fcap,mcap=installation_caps(int(planet.population or 0),economy)
    factories=int(planet.factories or 0)
    mines=int(planet.mines or 0)
    return {
        "population":int(planet.population or 0),
        "factory_cap":fcap,
        "mine_cap":mcap,
        "factories":factories,
        "mines":mines,
        "factory_headroom":max(0,fcap-factories),
        "mine_headroom":max(0,mcap-mines),
        "factory_overbuilt":max(0,factories-fcap),
        "mine_overbuilt":max(0,mines-mcap),
        "factories_fully_utilized":factories>=fcap,
        "mines_fully_utilized":mines>=mcap,
    }


def estimated_operating_resources(planet,economy:RaceEconomy) -> dict:
    """
    Estimate the resources currently generated by population + OPERABLE factories.
    This is for planning/reporting only, not native accounting.
    """
    status=installation_status(planet,economy)
    operated_factories=min(status["factories"],status["factory_cap"])
    pop_resources=int(planet.population or 0)//max(1,economy.colonists_per_resource)
    factory_resources=(operated_factories*economy.factory_output_per_10)//10
    return {
        **status,
        "operated_factories":operated_factories,
        "population_resources":pop_resources,
        "factory_resources":factory_resources,
        "estimated_resources":pop_resources+factory_resources,
    }


def mineral_surface_stock(planet) -> dict[str,int]:
    """Return the observed I/B/G stock on a planet in kT."""
    return {
        mineral:max(0,int(getattr(planet,mineral,0) or 0))
        for mineral in MINERAL_TYPES
    }


def mineral_concentrations(planet) -> dict[str,int|None]:
    """Return observed I/B/G concentrations without inventing missing intel."""
    raw=list((getattr(planet,"native",{}) or {}).get("mineral_concentrations",[]) or [])
    values=[]
    for index in range(3):
        value=raw[index] if index<len(raw) else None
        try:
            values.append(max(0,int(value)) if value is not None else None)
        except (TypeError,ValueError):
            values.append(None)
    return dict(zip(MINERAL_TYPES,values,strict=True))


def estimated_mineral_output(planet,economy:RaceEconomy) -> dict:
    """
    Estimate this year's extractable kT for each mineral.

    This deliberately follows the StarsAPI/Nova implementation: only complete
    groups of ten operable mines count, then each group produces the race's
    ``mine_output_per_10`` scaled by the observed concentration.  The result
    is planning/reporting data; it never changes native mineral accounting.
    """
    status=installation_status(planet,economy)
    operated_mines=min(int(status["mines"]),int(status["mine_cap"]))
    mine_groups=max(0,operated_mines//10)
    concentrations=mineral_concentrations(planet)
    output={
        mineral:(
            (mine_groups*int(economy.mine_output_per_10)*int(concentration))//100
            if concentration is not None else None
        )
        for mineral,concentration in concentrations.items()
    }
    return {
        **status,
        "operated_mines":operated_mines,
        "mine_groups_of_ten":mine_groups,
        "concentrations":concentrations,
        "estimated_mineral_output":output,
    }


def is_economic_core(planet) -> bool:
    """True for a homeworld or an operational refuel/shipbuilding hub."""
    native=getattr(planet,"native",{}) or {}
    base=native.get("starbase_capabilities") or {}
    return bool(
        native.get("is_homeworld")
        or base.get("can_build_ships")
        or base.get("can_refuel")
    )


def working_mineral_reserve(
    planet,
    economy:RaceEconomy,
    queue=(),
    *,
    is_core:bool|None=None,
) -> dict:
    """
    Mineral stock that should remain available for normal planetary work.

    This is a conservative planning reserve, not a guessed design bill.  It
    protects core worlds and active shipyards from being drained by transports,
    reserves Germanium for queued factories exactly, and gives every colony a
    modest working stock.  Core classification is derived from native world
    state, never from a persona or playstyle.
    """
    queue=list(queue or [])
    core=is_economic_core(planet) if is_core is None else bool(is_core)
    status=installation_status(planet,economy)
    factories_queued=sum(
        max(0,int(item.get("quantity",0) or 0))
        for item in queue if item.get("item")=="factory"
    )
    defenses_queued=sum(
        max(0,int(item.get("quantity",0) or 0))
        for item in queue if item.get("item")=="defense"
    )
    ships_queued=sum(
        max(0,int(item.get("quantity",0) or 0))
        for item in queue if item.get("item")=="ship_design"
    )
    bases_queued=sum(
        max(0,int(item.get("quantity",0) or 0))
        for item in queue if item.get("item")=="starbase_design"
    )

    # Keep the historic small-colony baseline, but retain a genuine working
    # reserve at cores so a freighter cannot strip an active production hub.
    pop_band=max(1,int(getattr(planet,"population",0) or 0)//100000)
    baseline=min(60,15+5*pop_band)
    if core:
        base={"ironium":300,"boranium":220,"germanium":220}
    else:
        base={mineral:baseline for mineral in MINERAL_TYPES}

    g_per_factory=3 if economy.factory_germanium_discount else 4
    factory_germanium=factories_queued*g_per_factory
    defense_minerals=defenses_queued*5

    # Exact ship/starbase mineral bills are not present in all normalized game
    # states.  These are intentionally labelled reserve allowances rather than
    # claims about a particular design's actual cost.
    ship_reserve=ships_queued*(90 if core else 30)
    starbase_reserve=bases_queued*(180 if core else 80)
    return {
        "ironium":base["ironium"]+defense_minerals+ship_reserve+starbase_reserve,
        "boranium":base["boranium"]+defense_minerals+ship_reserve+starbase_reserve,
        "germanium":base["germanium"]+factory_germanium+defense_minerals+ship_reserve+starbase_reserve,
        "factory_germanium":factory_germanium,
        "queued_factories":factories_queued,
        "queued_ships":ships_queued,
        "queued_starbases":bases_queued,
        "core":core,
        "factory_headroom":int(status["factory_headroom"]),
        "mine_headroom":int(status["mine_headroom"]),
    }


def factory_germanium_floor(planet, economy:RaceEconomy, *, is_core:bool|None=None) -> int:
    """Surface Germanium the factory planner must not spend this turn."""
    core=is_economic_core(planet) if is_core is None else bool(is_core)
    # Small colonies retain the historical eight-kT floor.  A core protects a
    # useful Germanium reserve before converting minerals into factories.
    return 220 if core else max(8,2*(3 if economy.factory_germanium_discount else 4))


# --- Population carrying capacity / growth ---

def theoretical_max_population(race) -> int:
    """
    Stars! nominal carrying capacity is 1,000,000 colonists, modified by race:
      HE   x 0.5
      JOAT x 1.2
      OBRM x 1.1

    These modifiers stack the same way StarsAPI's Race.getMaxPopulation() does.
    """
    native=getattr(race,"native",{}) or {}
    prt_id=int(native.get("prt_id",-1))
    prt=str(getattr(race,"primary_trait","") or "")
    lrts=set(native.get("lrts",[]) or [])

    max_pop=1_000_000.0
    if prt_id==0 or "Hyper Expansion" in prt:
        max_pop *= 0.5
    if prt_id==9 or "Jack of All Trades" in prt:
        max_pop *= 1.2
    if "OBRM" in lrts:
        max_pop *= 1.1
    return int(max_pop)


def planet_population_capacity(planet,race) -> int:
    """
    Green/yellow worlds use the race's carrying capacity.
    A red (negative-habitability) world uses Stars!' special 25,000 ceiling
    for crowding/death calculations.
    """
    hab=getattr(planet,"habitability",None)
    if hab is not None and int(hab) < 0:
        return 25_000
    return theoretical_max_population(race)


def population_capacity_fraction(planet,race) -> float:
    cap=max(1,planet_population_capacity(planet,race))
    # StarsAPI/Technical FAQ behavior uses CEIL to an integer capacity percent.
    pop=max(0,int(getattr(planet,"population",0) or 0))
    pct=math.ceil((pop/cap)*100.0)
    return pct/100.0


def projected_population_growth(planet,race) -> int:
    """
    Stars! crowding-aware annual population growth.

    Source model follows StarsAPI Star.CalculateGrowth:
      - <=25% capacity: nominal growth
      - 25-100%: crowding factor 16/9 * (1-capacity)^2
      - 100%: zero
      - over capacity: crowding deaths
      - growth/death is rounded to 100-colonist units

    Habitability is represented in our normalized model as -15..100%.
    """
    pop=max(0,int(getattr(planet,"population",0) or 0))
    if pop<=0:
        return 0

    hab_raw=getattr(planet,"habitability",None)
    if hab_raw is None:
        return 0
    hab=max(-1.0,min(1.0,float(hab_raw)/100.0))

    growth_rate=float(getattr(race,"growth_rate",0.15) or 0.15)
    native=getattr(race,"native",{}) or {}
    prt_id=int(native.get("prt_id",-1))
    prt=str(getattr(race,"primary_trait","") or "")
    if prt_id==0 or "Hyper Expansion" in prt:
        growth_rate *= 2.0

    capacity=population_capacity_fraction(planet,race)

    if hab < 0:
        growth=0.1*pop*hab
    elif capacity <= 0.25:
        growth=pop*growth_rate*hab
    elif capacity < 1.0:
        growth=pop*growth_rate*hab
        growth *= (16.0/9.0)*(1.0-capacity)*(1.0-capacity)
    elif capacity == 1.0:
        growth=0.0
    elif capacity < 4.0:
        growth=pop*(capacity-1.0)*-4.0/100.0
    else:
        growth=pop*-0.12

    # Vanilla Stars! tracks population in 100-colonist increments.
    final=int(growth)
    final=int(final/100)*100
    return final


def projected_next_population(planet,race) -> int:
    return max(0,int(getattr(planet,"population",0) or 0)+projected_population_growth(planet,race))
